name: 'Telepresence Disconect'
description: 'Diconnects telepresence from the current remote cluster'
runs:
  using: "composite"
  steps:
    - name: Disconnect from remote cluster
      shell: bash
      run: telepresence quit

